-- One-time setup for a brand-new, isolated Snowflake identity for the
-- Dealership Inventory app. Run this as ACCOUNTADMIN (or a role that can
-- CREATE USER / CREATE DATABASE / CREATE WAREHOUSE).
--
-- Everything below only CREATEs new objects (database, warehouse, role, user).
-- It does not touch TFC_PAYROLL, CALL_LOGGER_DB, ANUBISBLUEDESIGNS, or
-- call_logger_app in any way — this app gets its own fully separate identity,
-- so nothing here can affect the payroll or call-logger projects.

CREATE DATABASE IF NOT EXISTS TFC_INVENTORY;
CREATE SCHEMA IF NOT EXISTS TFC_INVENTORY.INVENTORY;

CREATE WAREHOUSE IF NOT EXISTS INVENTORY_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE ROLE IF NOT EXISTS INVENTORY_APP_ROLE;

GRANT USAGE ON WAREHOUSE INVENTORY_WH TO ROLE INVENTORY_APP_ROLE;
GRANT USAGE ON DATABASE TFC_INVENTORY TO ROLE INVENTORY_APP_ROLE;
GRANT ALL ON SCHEMA TFC_INVENTORY.INVENTORY TO ROLE INVENTORY_APP_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA TFC_INVENTORY.INVENTORY TO ROLE INVENTORY_APP_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA TFC_INVENTORY.INVENTORY TO ROLE INVENTORY_APP_ROLE;

CREATE USER IF NOT EXISTS INVENTORY_APP
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw9WXFI9UIW5QILriVdtLAwa3zrhGgYcelTOPlYK1KXYfFV4PoLbvZe4jGNALOdu/9DbyNN+dZj59e2pprcw+fDQLthFaMbfsvIfBBkG0v5UFWNQtly8hyCSVwOkGOYQCdrMI8t08szryLtht4pWknHMD1rhnEGlOhZbe0hEnxNYK/aoLR6pFh0MLAGfECHvEp1OxEYS1s/+YcdfFQVoGv6Umh08eyNUF8lbkEf1OCrSSoOGpHckpS9Sk3C0T4BRO6qDov55B0iOxZnUVTXkPKayr9ThNbAz4uzak+F7ee2eSJxqX4MawBBNUVR+FhfwQFLusR6CzAOe4VAE2lkvanwIDAQAB'
  DEFAULT_ROLE = INVENTORY_APP_ROLE
  DEFAULT_WAREHOUSE = INVENTORY_WH
  DEFAULT_NAMESPACE = TFC_INVENTORY.INVENTORY
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE INVENTORY_APP_ROLE TO USER INVENTORY_APP;
